all:
	pandoc -i ./index.md -o ./index.html
	pandoc -i ./introBioinformaticsAidanBudd.md -o ./introBioinformaticsAidanBudd.html
	pandoc -i ./introToTheCourseAidanBudd.md -o ./introToTheCourseAidanBudd.html